disabled_rules:
  - trailing_comma
  - empty_enum_arguments
  - void_return
  - redundant_optional_initialization
  - nesting
  - redundant_discardable_let
  - opening_brace
  - multiple_closures_with_trailing_closure
excluded:
  - Pods
line_length:
  warning: 140
  error: 140
identifier_name:
  excluded:
    - 'id'
    - 'i'
    - 'x'
    - 'y'
    - 'z'
type_name:
  max_length: 60
